/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ../public/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
       <pointLight intensity={54351.41} decay={2} position={[3.35, 3.37, -2.75]} rotation={[-1.84, 0.6, 1.93]} />
       <pointLight intensity={543.51} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
         {/* <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.9} position={[12.99, 6.94, 8.69]} rotation={[-0.5, 0.75, 0.35]} /> */}
     
      <mesh geometry={nodes.fuselage01.geometry} material={materials.base} position={[0, 1.271, 2.867]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.engine01.geometry} material={materials.internals_b} position={[-0.096, 0, 0.038]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.engine02.geometry} material={materials.internals_alu} position={[-0.204, 0, 0.038]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.engine03.geometry} material={materials.internals_alu} position={[-0.204, 0, 0.28]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.engine04.geometry} material={materials.internals_alu} position={[-0.203, -0.086, 0.32]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.engine05.geometry} material={materials.internals_b} position={[-0.07, 0, 0.038]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.engine06.geometry} material={materials.internals_alu} position={[-0.07, 0, 0.038]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.engine07.geometry} material={materials.internals_alu} position={[-0.07, -0.01, 0.038]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.engine08.geometry} material={materials.internals_b} position={[-0.07, -0.01, 0.038]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.exhaust.geometry} material={materials.internals_alu} position={[0.432, -0.184, 0.443]} rotation={[0.373, -1.349, Math.PI / 2]} />
        <mesh geometry={nodes.fuselage02.geometry} material={materials.base}>
          <mesh geometry={nodes.fuselage_lock01001.geometry} material={materials.base} position={[0, 0.297, 0.289]} rotation={[2.357, -1.364, 1.507]}>
            <mesh geometry={nodes.fuselage_lock02001.geometry} material={materials.internals_alu} position={[0.041, -0.003, 0]} rotation={[0, 0, -0.275]}>
              <mesh geometry={nodes['pin02-1001'].geometry} material={materials.internals_alu} position={[0.046, 0.001, 0]}>
                <mesh geometry={nodes['pin02-2'].geometry} material={materials.internals_alu} position={[0, 0.004, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.fuselage_lock01002.geometry} material={materials.base} position={[0.383, -0.354, 0.345]} rotation={[0.764, 1.37, 1.726]}>
            <mesh geometry={nodes.fuselage_lock02003.geometry} material={materials.internals_alu} position={[0.041, -0.003, 0]} rotation={[0, 0, -0.21]}>
              <mesh geometry={nodes['pin02-1003'].geometry} material={materials.internals_alu} position={[0.046, 0.001, 0]}>
                <mesh geometry={nodes['pin02-2003'].geometry} material={materials.internals_alu} position={[0, 0.004, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.fuselage_lock01003.geometry} material={materials.base} position={[0, -0.297, 0.289]} rotation={[0.802, 1.38, 1.501]}>
            <mesh geometry={nodes.fuselage_lock02002.geometry} material={materials.internals_alu} position={[0.041, -0.003, 0]} rotation={[0, 0, -0.275]}>
              <mesh geometry={nodes['pin02-1002'].geometry} material={materials.internals_alu} position={[0.046, 0.001, 0]}>
                <mesh geometry={nodes['pin02-2002'].geometry} material={materials.internals_alu} position={[0, 0.004, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.fuselage_lock01.geometry} material={materials.base} position={[0.383, 0.354, 0.345]} rotation={[2.364, -1.352, 1.712]}>
            <mesh geometry={nodes.fuselage_lock02.geometry} material={materials.internals_alu} position={[0.041, -0.003, 0]} rotation={[0, 0, -0.21]}>
              <mesh geometry={nodes['pin02-1'].geometry} material={materials.internals_alu} position={[0.046, 0.001, 0]}>
                <mesh geometry={nodes['pin02-2001'].geometry} material={materials.internals_alu} position={[0, 0.004, 0]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.prop_tip01.geometry} material={materials.base} position={[-0.48, 0, 0.038]} rotation={[Math.PI / 4, 0, Math.PI / 2]}>
            <mesh geometry={nodes.prop01.geometry} material={materials.prop} position={[0, -0.196, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh geometry={nodes.prop02.geometry} material={materials.prop} position={[0, -0.196, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.prop_tip02.geometry} material={materials.base} position={[0, -0.218, 0]} rotation={[0, Math.PI / 4, 0]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.fuselage03.geometry} material={materials.base}>
          <mesh geometry={nodes.engine09.geometry} material={materials.internals_b} position={[-0.014, 0, 0.449]} rotation={[0, 0.15, Math.PI / 2]}>
            <mesh geometry={nodes.engine10.geometry} material={materials.internals_b} position={[0, 0.066, 0]} />
          </mesh>
          <mesh geometry={nodes.fuselage04.geometry} material={materials.base} />
          <mesh geometry={nodes.fuselage05.geometry} material={materials.base} />
          <mesh geometry={nodes.fuselage06.geometry} material={materials.base} />
        </mesh>
        <mesh geometry={nodes.fuselage07.geometry} material={materials.base} position={[-0.184, 0, 0.301]} />
        <mesh geometry={nodes.fuselage08.geometry} material={materials.base} position={[1.365, 0, -0.347]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.fuselage09.geometry} material={materials.base} position={[1.776, 0, -0.757]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.fuselage10.geometry} material={materials.base} />
        <mesh geometry={nodes.fuselage11.geometry} material={materials.base} />
        <mesh geometry={nodes.fuselage12.geometry} material={materials.base} position={[1.166, -0.323, 0.598]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.undercarriage_R05.geometry} material={materials.base} position={[0.048, -0.006, 0]} rotation={[Math.PI, 0, 2.235]} />
        </mesh>
        <mesh geometry={nodes.fuselage13.geometry} material={materials.base} position={[1.166, 0.323, 0.598]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.undercarriage_L05.geometry} material={materials.base} position={[-0.048, -0.006, 0]} rotation={[0, 0, -0.906]} />
        </mesh>
        <mesh geometry={nodes.fuselage14.geometry} material={materials.base} position={[1.71, -0.318, 0.6]} rotation={[1.582, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.fuselage15.geometry} material={materials.base} position={[1.71, 0.318, 0.6]} rotation={[1.56, 0, Math.PI / 2]} />
        <mesh geometry={nodes.fuselage16.geometry} material={materials.base} position={[5.574, 0.102, -0.058]} rotation={[-1.047, -1.434, -1.198]} />
        <mesh geometry={nodes.fuselage_door.geometry} material={materials.base} />
        <mesh geometry={nodes.fuselage_door02.geometry} material={materials.base} />
        <mesh geometry={nodes.fuselage_wings.geometry} material={materials.base} position={[1.712, 0, -0.696]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.aileron_L01.geometry} material={materials.base} position={[3.492, -0.041, -0.671]}>
            <mesh geometry={nodes.aileron_L02.geometry} material={materials.base} position={[-0.136, -0.081, -0.096]}>
              <mesh geometry={nodes.wing_wire_L02.geometry} material={materials.base} position={[0, -0.045, 0.023]} rotation={[-0.156, -0.054, 1.562]} />
            </mesh>
            <mesh geometry={nodes.aileron_L03.geometry} material={materials.base} position={[-0.136, 0.031, -0.101]} rotation={[-0.224, 0, 0]}>
              <mesh geometry={nodes.wing_wire_L03.geometry} material={materials.base} rotation={[-0.007, 0, 1.571]} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.aileron_L04.geometry} material={materials.base} position={[3.356, 0.074, -0.402]} rotation={[-0.192, 0, 0]} />
          <mesh geometry={nodes.aileron_R04.geometry} material={materials.base} position={[-3.356, 0.074, -0.402]} rotation={[-0.192, 0, 0]} />
          <mesh geometry={nodes.aileron_R01.geometry} material={materials.base} position={[-3.492, -0.041, -0.671]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.aileron_R02.geometry} material={materials.base} position={[-0.136, -0.081, 0.096]} rotation={[-Math.PI, 0, Math.PI]}>
              <mesh geometry={nodes.wing_wire_R02.geometry} material={materials.base} position={[0, -0.045, 0.023]} rotation={[-0.156, 0.054, 1.579]} />
            </mesh>
            <mesh geometry={nodes.aileron_R03.geometry} material={materials.base} position={[-0.136, 0.031, 0.101]} rotation={[0.224, 0, Math.PI]}>
              <mesh geometry={nodes.wing_wire_R03.geometry} material={materials.base} rotation={[3.135, 0, 1.571]} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.flap_L01.geometry} material={materials.base} position={[1.634, -0.124, -0.756]}>
            <mesh geometry={nodes.flap_L02.geometry} material={materials.base} position={[-0.799, 0.003, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.pin01001.geometry} material={materials.base} position={[0.013, -0.01, 0]} />
            </mesh>
            <mesh geometry={nodes.flap_L03.geometry} material={materials.base} position={[0.01, 0.013, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.pin01.geometry} material={materials.base} position={[0.013, -0.01, 0]} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.flap_R01.geometry} material={materials.base} position={[-1.634, -0.124, -0.756]}>
            <mesh geometry={nodes.flap_R02.geometry} material={materials.base} position={[0.799, 0.003, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.pin01002.geometry} material={materials.base} position={[0.013, 0.01, 0]} />
            </mesh>
            <mesh geometry={nodes.flap_R03.geometry} material={materials.base} position={[-0.01, 0.013, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.pin01003.geometry} material={materials.base} position={[0.013, 0.01, 0]} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.wing_light_L01.geometry} material={materials.base} position={[5.126, -0.001, 0.405]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.wing_light_L02.geometry} material={materials.glass} />
            <mesh geometry={nodes.wing_light_L03.geometry} material={materials.mirror} position={[0, 0.047, 0]} />
          </mesh>
          <mesh geometry={nodes.wing_light_R01.geometry} material={materials.base} position={[-5.126, -0.001, 0.405]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.wing_light_R02.geometry} material={materials.glass} />
            <mesh geometry={nodes.wing_light_R03.geometry} material={materials.mirror} position={[0, 0.047, 0]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.fuselage_wings02.geometry} material={materials.base} position={[1.712, 0, -0.696]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.horizontal_stab01.geometry} material={materials.base} position={[5.693, 0, -0.323]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.elevator01.geometry} material={materials.base} position={[0, 0.023, -0.272]} />
        </mesh>
        <mesh geometry={nodes.interior_frame01.geometry} material={materials.internals_b} position={[1.388, 0, -0.719]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.interior_frame02.geometry} material={materials.internals_b} position={[1.379, 0.307, -0.698]} rotation={[1.23, 0.603, -1.989]} />
        <mesh geometry={nodes.interior_frame03.geometry} material={materials.internals_b} position={[1.379, -0.307, -0.698]} rotation={[1.306, -0.253, 0.891]} />
        <mesh geometry={nodes.interior_panel.geometry} material={materials.internals_b} position={[0.719, 0, -0.208]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.interior_seat.geometry} material={materials.internals_b} position={[1.179, 0, 0.359]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.pin03.geometry} material={materials.base} position={[5.875, 0.025, -0.886]} rotation={[2.117, Math.PI / 2, 0]}>
          <mesh geometry={nodes.rudder10.geometry} material={materials.base} position={[0.011, 0.004, 0]}>
            <mesh geometry={nodes.wire_L01.geometry} material={materials.base} position={[0.041, -0.004, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.rudder09.geometry} material={materials.base} position={[-0.004, 0.953, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
            </mesh>
          </mesh>
        </mesh>
        <mesh geometry={nodes.pin03001.geometry} material={materials.base} position={[5.875, -0.025, -0.886]} rotation={[1.024, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.rudder13.geometry} material={materials.base} position={[0.011, 0.004, 0]}>
            <mesh geometry={nodes.wire_R01.geometry} material={materials.base} position={[0.041, -0.004, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.rudder12.geometry} material={materials.base} position={[-0.004, 0.953, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
            </mesh>
          </mesh>
        </mesh>
        <mesh geometry={nodes.rudder01.geometry} material={materials.base} position={[6.017, 0, -0.036]}>
          <mesh geometry={nodes.rudder02.geometry} material={materials.base} position={[0.081, 0, -0.078]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.pin06.geometry} material={materials.base} position={[0.06, 0, 0]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.rudder03.geometry} material={materials.base} position={[0.035, -0.001, 0]} rotation={[0, 1.571, 0]}>
                <mesh geometry={nodes.rudder_wire_L.geometry} material={materials.base} rotation={[1.675, -0.005, 1.522]}>
                  <mesh geometry={nodes.pin07001.geometry} material={materials.base} position={[0.027, 0.001, -0.002]} rotation={[0.005, 0.005, 1.595]} />
                </mesh>
              </mesh>
            </mesh>
            <mesh geometry={nodes.pin06001.geometry} material={materials.base} position={[-0.06, 0, 0]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.rudder04.geometry} material={materials.base} position={[0.035, -0.001, 0]} rotation={[0, 1.571, 0]}>
                <mesh geometry={nodes.rudder_wire_R.geometry} material={materials.base} rotation={[1.675, 0.005, 1.619]}>
                  <mesh geometry={nodes.pin07.geometry} material={materials.base} position={[0.027, -0.001, -0.002]} rotation={[-0.005, 0.005, 1.591]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.undercarriage_tail02.geometry} material={materials.internals_alu} position={[0, 0, 0.001]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.rudder_spring_L.geometry} material={materials.internals_alu} position={[0.052, -0.018, -0.006]} rotation={[-0.369, -0.028, 3.13]} scale={[0.994, 0.994, 1.012]} />
            <mesh geometry={nodes.rudder_spring_R.geometry} material={materials.internals_alu} position={[-0.052, -0.018, -0.006]} rotation={[-0.369, 0.031, -3.13]} scale={[0.994, 0.994, 1.012]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.rudder05.geometry} material={materials.internals_alu} position={[5.875, 0, -0.027]} rotation={[0, -1.417, Math.PI / 2]}>
          <mesh geometry={nodes.pin05.geometry} material={materials.base} position={[-0.079, 0.005, 0]} rotation={[2.988, 0, -2.788]}>
            <mesh geometry={nodes.rudder07.geometry} material={materials.base} position={[0.011, 0.004, 0]}>
              <mesh geometry={nodes.wire_R02.geometry} material={materials.base} position={[0.041, -0.004, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh geometry={nodes.rudder11.geometry} material={materials.base} position={[-0.004, 0.803, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes.pin04001.geometry} material={materials.base} position={[0.01, 0.011, 0]} rotation={[0, 0, 0.353]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.pin05001.geometry} material={materials.base} position={[0.079, 0.005, 0]} rotation={[-0.154, 0, 0.353]}>
            <mesh geometry={nodes.rudder06.geometry} material={materials.base} position={[0.011, 0.004, 0]}>
              <mesh geometry={nodes.wire_L02.geometry} material={materials.base} position={[0.041, -0.004, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh geometry={nodes.rudder08.geometry} material={materials.base} position={[-0.004, 0.803, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes.pin04.geometry} material={materials.base} position={[0.01, 0.011, 0]} rotation={[0, 0, 0.353]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
        </mesh>
        <mesh geometry={nodes.rudder_frame01.geometry} material={materials.internals_alu} position={[6, 0, -0.036]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.rudder_frame02.geometry} material={materials.internals_alu} position={[6, 0, -0.047]} rotation={[0.023, -0.703, 1.325]} />
        <mesh geometry={nodes.rudder_frame03.geometry} material={materials.internals_alu} position={[6, 0, -0.047]} rotation={[-0.023, -0.703, 1.817]} />
        <mesh geometry={nodes.rudder_frame04.geometry} material={materials.internals_alu} position={[6, 0, -0.046]} rotation={[0.017, 0.123, 1.43]} />
        <mesh geometry={nodes.rudder_frame05.geometry} material={materials.internals_alu} position={[6, 0, -0.046]} rotation={[-0.017, 0.123, 1.711]} />
        <mesh geometry={nodes.undercarriage02.geometry} material={materials.base} position={[1.183, 0, 0.826]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.undercarriage01.geometry} material={materials.base} position={[0, 0.03, 0]}>
            <mesh geometry={nodes.undercarriage_L03.geometry} material={materials.base} position={[0.037, -0.014, 0]} rotation={[-Math.PI / 2, 0.001, 1.215]}>
              <mesh geometry={nodes.undercarriage_L04.geometry} material={materials.base} position={[0, -0.256, -0.004]} rotation={[-0.002, 0, -Math.PI / 2]} />
            </mesh>
            <mesh geometry={nodes.undercarriage_R03.geometry} material={materials.base} position={[-0.037, -0.014, 0]} rotation={[Math.PI / 2, 0.001, -1.927]}>
              <mesh geometry={nodes.undercarriage_R04.geometry} material={materials.base} position={[0, -0.255, 0.004]} rotation={[0, 0.001, -1.571]} />
            </mesh>
          </mesh>
        </mesh>
        <mesh geometry={nodes.undercarriage_L01.geometry} material={materials.base} position={[1.165, 0.323, 0.597]} rotation={[-2.316, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.undercarriage_L02.geometry} material={materials.base} position={[-0.067, -0.562, -0.003]} rotation={[-3.141, 0, -0.47]} />
          <group position={[0.097, -0.713, -0.003]} rotation={[Math.PI / 2, -0.745, 0]}>
            <mesh geometry={nodes.Plane.geometry} material={materials.tires} />
            <mesh geometry={nodes.Plane_1.geometry} material={materials.base} />
          </group>
          <mesh geometry={nodes.wheel_L02.geometry} material={materials.internals_alu} position={[0.022, -0.644, -0.003]} rotation={[0, 0, -2.316]} />
          <mesh geometry={nodes.wheel_L03.geometry} material={materials.internals_alu} position={[0.034, -0.655, -0.003]} rotation={[0, 0, -2.316]} />
        </mesh>
        <mesh geometry={nodes.undercarriage_R01.geometry} material={materials.base} position={[1.165, -0.323, 0.597]} rotation={[-0.826, 1.57, 0]}>
          <mesh geometry={nodes.undercarriage_R02.geometry} material={materials.base} position={[-0.067, -0.562, 0.003]} rotation={[3.141, 0, -0.47]} />
          <group position={[0.097, -0.713, 0.003]} rotation={[-Math.PI / 2, 0.745, Math.PI]}>
            <mesh geometry={nodes.Plane022.geometry} material={materials.tires} />
            <mesh geometry={nodes.Plane022_1.geometry} material={materials.base} />
            <mesh geometry={nodes.wheel_R02.geometry} material={materials.internals_alu} position={[0.103, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh geometry={nodes.wheel_R03.geometry} material={materials.internals_alu} position={[0, 0.017, 0]} />
            </mesh>
          </group>
        </mesh>
        <mesh geometry={nodes.undercarriage_tail01.geometry} material={materials.internals_b} position={[5.898, 0, -0.011]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.undercarriage_tail03.geometry} material={materials.internals_alu} position={[0, -0.016, -0.114]} rotation={[-0.276, 0, 0]}>
            <mesh geometry={nodes.undercarriage_tail04.geometry} material={materials.internals_alu} position={[0, -0.002, -0.2]} rotation={[0.424, 0, 0]}>
              <mesh geometry={nodes.undercarriage_tail05.geometry} material={materials.internals_alu} position={[0, -0.01, -0.011]} rotation={[Math.PI / 2, 0, 0]}>
                <group position={[0.058, 0.004, -0.019]} rotation={[-1.57, 0, 0]} scale={[1.33, 1, 1]}>
                  <mesh geometry={nodes.undercarriage_tail_wire_L02.geometry} material={materials.internals_alu} position={[0, 0, 0.005]} rotation={[-0.51, -0.031, 1.562]} scale={[1.318, 0.752, 1.016]}>
                    <mesh geometry={nodes.undercarriage_wire_L01.geometry} material={materials.internals_alu} position={[0, 0, 0.006]} rotation={[0, 0, Math.PI / 2]} />
                  </mesh>
                </group>
                <group position={[-0.058, 0.004, -0.019]} rotation={[-1.57, 0, 0]} scale={[1.33, 1, 1]}>
                  <mesh geometry={nodes.undercarriage_tail_wire_R02.geometry} material={materials.internals_alu} position={[0, 0, 0.005]} rotation={[-0.509, 0.033, 1.58]} scale={[1.318, 0.752, 1.016]}>
                    <mesh geometry={nodes.undercarriage_tail_wire_R01.geometry} material={materials.internals_alu} position={[0, 0, 0.006]} rotation={[0, 0, Math.PI / 2]} />
                  </mesh>
                </group>
                <group position={[0, -0.092, 0.093]} rotation={[-1.57, 0, -Math.PI / 2]}>
                  <mesh geometry={nodes.Cylinder013.geometry} material={materials.tires} />
                  <mesh geometry={nodes.Cylinder013_1.geometry} material={materials.internals_alu} />
                </group>
              </mesh>
            </mesh>
          </mesh>
        </mesh>
        <mesh geometry={nodes.windshield01.geometry} material={materials.glass} />
        <mesh geometry={nodes.windshield02.geometry} material={materials.glass} />
        <mesh geometry={nodes.wing_support_L01.geometry} material={materials.base} position={[1.718, 0.35, 0.574]} rotation={[-Math.PI / 2, -1.431, 0.379]}>
          <mesh geometry={nodes.nut01002.geometry} material={materials.base} position={[0.088, 0.001, 0.034]} rotation={[3.045, 0.237, -1.555]}>
            <mesh geometry={nodes.wing_support_L09.geometry} material={materials.base} position={[0, -0.016, 0]} />
          </mesh>
          <mesh geometry={nodes.nut01003.geometry} material={materials.base} position={[0.093, 0, -0.009]} rotation={[-3.141, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.wing_support_L08.geometry} material={materials.base} position={[0, -0.016, 0]} />
          </mesh>
          <mesh geometry={nodes.wing_support_L05.geometry} material={materials.base}>
            <mesh geometry={nodes.wing_support_L02.geometry} material={materials.base} position={[1.526, 0.052, 0.174]} rotation={[1.526, -0.053, 0.13]} />
            <mesh geometry={nodes.wing_support_L03.geometry} material={materials.base} position={[1.505, 0.077, 0.357]} rotation={[0.202, -0.224, -0.337]}>
              <mesh geometry={nodes.wing_support_L11.geometry} material={materials.base} position={[0, 0.532, 0.001]} rotation={[-0.267, 0, -Math.PI / 2]} />
            </mesh>
            <mesh geometry={nodes.wing_support_L04.geometry} material={materials.base} position={[1.553, 0.057, -0.013]} rotation={[-0.364, 0, -0.402]}>
              <mesh geometry={nodes.wing_support_L10.geometry} material={materials.base} position={[0, 0.543, 0.001]} rotation={[0.337, 0, -Math.PI / 2]} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.wing_support_L06.geometry} material={materials.base} position={[3.077, 0.034, 0.716]} rotation={[-0.052, -0.13, -0.382]}>
            <mesh geometry={nodes.aileron_controll_L01.geometry} material={materials.base} position={[-0.018, -0.011, -0.01]} rotation={[Math.PI / 2, 0.373, -Math.PI]}>
              <mesh geometry={nodes.aileron_controll_L02.geometry} material={materials.base} position={[0.06, 0.076, 0]} rotation={[-Math.PI / 2, Math.PI / 4, 0]}>
                <mesh geometry={nodes.aileron_controll_L03.geometry} material={materials.base} position={[0, 0, -0.039]} />
                <mesh geometry={nodes.aileron_controll_L04.geometry} material={materials.base} position={[0, 0, 0.028]}>
                  <mesh geometry={nodes.aileron_controll_L05.geometry} material={materials.base} position={[0, 0, 0.001]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.wing_support_L07.geometry} material={materials.base} position={[3.172, -0.004, -0.014]} rotation={[-0.052, -0.13, -0.382]}>
            <mesh geometry={nodes.pin08.geometry} material={materials.base} position={[-0.018, -0.011, -0.003]} rotation={[Math.PI / 2, 0.373, -Math.PI]} />
          </mesh>
          <mesh geometry={nodes.wing_wire_L01.geometry} material={materials.base} position={[0.037, 0.018, -0.034]} rotation={[-0.052, -0.13, -0.382]} />
        </mesh>
        <mesh geometry={nodes.wing_support_R01.geometry} material={materials.base} position={[1.718, -0.35, 0.574]} rotation={[-Math.PI / 2, 1.431, -2.763]}>
          <mesh geometry={nodes.nut01.geometry} material={materials.base} position={[-0.088, -0.001, -0.034]} rotation={[3.045, 0.237, -1.555]}>
            <mesh geometry={nodes.wing_support_R09.geometry} material={materials.base} position={[0, 0.016, 0]} />
          </mesh>
          <mesh geometry={nodes.nut01001.geometry} material={materials.base} position={[-0.093, 0, 0.009]} rotation={[-3.141, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.wing_support_R08.geometry} material={materials.base} position={[0, 0.016, 0]} />
          </mesh>
          <mesh geometry={nodes.wing_support_R05.geometry} material={materials.base}>
            <mesh geometry={nodes.wing_support_R02.geometry} material={materials.base} position={[-1.526, -0.052, -0.174]} rotation={[1.526, -0.053, 0.13]} />
            <mesh geometry={nodes.wing_support_R03.geometry} material={materials.base} position={[-1.505, -0.077, -0.357]} rotation={[0.202, -0.224, -0.337]}>
              <mesh geometry={nodes.wing_support_R11.geometry} material={materials.base} position={[0, -0.532, -0.001]} rotation={[-0.267, 0.014, -Math.PI / 2]} scale={-1} />
            </mesh>
            <mesh geometry={nodes.wing_support_R04.geometry} material={materials.base} position={[-1.553, -0.057, 0.013]} rotation={[-0.364, 0, -0.402]}>
              <mesh geometry={nodes.wing_support_R10.geometry} material={materials.base} position={[0, -0.543, -0.001]} rotation={[0.337, 0.015, -Math.PI / 2]} scale={-1} />
            </mesh>
          </mesh>
          <mesh geometry={nodes.wing_support_R06.geometry} material={materials.base} position={[-3.077, -0.034, -0.716]} rotation={[-0.052, -0.13, -0.382]}>
            <mesh geometry={nodes.aileron_controll_R01.geometry} material={materials.base} position={[0.018, 0.011, 0.01]} rotation={[Math.PI / 2, 0.373, -Math.PI]}>
              <mesh geometry={nodes.aileron_controll_R02.geometry} material={materials.base} position={[-0.06, -0.076, 0]} rotation={[-Math.PI / 2, Math.PI / 4, 0]}>
                <mesh geometry={nodes.aileron_controll_R03.geometry} material={materials.base} position={[0, 0, 0.039]} />
                <mesh geometry={nodes.aileron_controll_R04.geometry} material={materials.base} position={[0, 0, -0.028]}>
                  <mesh geometry={nodes.aileron_controll_R05.geometry} material={materials.base} position={[0, 0, -0.001]} />
                </mesh>
              </mesh>
            </mesh>
          </mesh>
          <mesh geometry={nodes.wing_support_R07.geometry} material={materials.base} position={[-3.172, 0.004, 0.014]} rotation={[-0.052, -0.13, -0.382]}>
            <mesh geometry={nodes.pin08001.geometry} material={materials.base} position={[0.018, 0.011, 0.003]} rotation={[Math.PI / 2, 0.373, -Math.PI]} />
          </mesh>
          <mesh geometry={nodes.wing_wire_R01.geometry} material={materials.base} position={[-0.037, -0.018, 0.034]} rotation={[-0.052, -0.13, -0.382]} />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/model.glb')
